---
title: "Data"
author: "Sara Park"
date: "10/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
oecd <- read_csv("DP_LIVE_14102020222633846.csv", 
                 col_types = cols(LOCATION = col_character(),
                                   INDICATOR = col_character(),
                                   SUBJECT = col_character(),
                                   MEASURE = col_character(),
                                   FREQUENCY = col_character(),
                                   TIME = col_double(),
                                   Value = col_double(),
                                   'Flag Codes' = col_logical())) %>% 
    select(LOCATION, SUBJECT, TIME, Value) 

oecd %>% 
    ggplot(aes(x = SUBJECT, y = Value)) +
    geom_text(aes(label = LOCATION))

un <- read_csv("finalproject/48 - Proportion of ever-partnered women and girls aged 15 years and older subjected to physical  sexual or psychological violence by a current or former intimate partner in the previous 12 months  by form of violence and by age_data")
```



